AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  todo-app

  Sample SAM Template for todo-app
  
Globals:
  Function:
    Timeout: 3

Resources:
  GetTodosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        GetTodos:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  GetTodosApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GetTodosFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt GetTodosFunction.Arn
  GetTodosFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GetTodosFunctionRole.Arn
